name: Daily Inventory Forecast

on:
  schedule:
    # Run every day at 9:00 AM IST (3:30 AM UTC)
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  generate-inventory-forecast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" | base64 --decode > service_account.json
          python inventory_forecast.py
        env:
          GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
          GMAIL_RECEIVER: kartik@theaffordableorganicstore.com
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          WC_CONSUMER_KEY: ${{ secrets.WC_CONSUMER_KEY }}
          WC_CONSUMER_SECRET: ${{ secrets.WC_CONSUMER_SECRET }} 